spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bookshelf?currentSchema=public
    username: bookshelf_app
    password: password1029384756
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 37d16ab913d0d1
    password: 5caa15fbbfbd91
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  security:
    jwt:
      secret: your-256-bit-secret-key-change-me-please
      expiration-ms: 86400000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.security: INFO
    com.example.bookshelf: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

server:
  port: 8081
  servlet:
    context-path: /api