spring:
  application:
    name: bookshelf
  datasource:
    url: jdbc:h2:mem:bookshelf
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080