spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bookshelf?currentSchema=public
    username: bookshelf_app
    password: password1029384756
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 37d16ab913d0d1
    password: 5caa15fbbfbd91
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    user:
      name: admin    # Удалите после реализации JWT (используется только для тестов)
      password: admin123  # Удалите после реализации JWT

jwt:
  secret: bXktc3VwZXItbG9uZy1yYW5kb20tc2VjcmV0LWtleS0xMjM0NTY=  # Сгенерируйте надежный ключ
  expiration: 86400000  # 24 часа в миллисекундах

app:
  verification-url: http://localhost:8081/api/v1/auth/verify?token=  # Обратите внимание на порт 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.security: INFO
    com.example.bookshelf: DEBUG

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha

recaptcha:
  secret: 6LewSoYrAAAAAO_AlnCgcHIPWB3PDRvNuCVAhtmB
  site: 6LewSoYrAAAAADatIyLzXtDZ-ot2WPMUlzN3sTt5